### ISSUE TITLE
可以告诉你的django版本还有python版本吗

### ISSUE THREAD

**Issue by chengkeke366** [snowWave666/Student_management#1]

**Comment by daxiongpro** [comment]
python manage.py runserver 报错了：
(django) D:\code\django\studentManage1\Student_management-master>python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\django\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\django\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\django\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\django\lib\site-packages\django\core\management\commands\runserver.py", line 109,
in inner_run
    autoreload.raise_last_exception()
  File "C:\ProgramData\Anaconda3\envs\django\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_excep
tion
    raise _exception[1]
  File "C:\ProgramData\Anaconda3\envs\django\lib\site-packages\django\core\management\__init__.py", line 357, in execute

    autoreload.check_errors(django.setup)()
  File "C:\ProgramData\Anaconda3\envs\django\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\django\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\ProgramData\Anaconda3\envs\django\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "C:\ProgramData\Anaconda3\envs\django\lib\site-packages\django\contrib\admin\apps.py", line 24, in ready
    self.module.autodiscover()
  File "C:\ProgramData\Anaconda3\envs\django\lib\site-packages\django\contrib\admin\__init__.py", line 26, in autodiscov
er
    autodiscover_modules('admin', register_to=site)
  File "C:\ProgramData\Anaconda3\envs\django\lib\site-packages\django\utils\module_loading.py", line 47, in autodiscover
_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\ProgramData\Anaconda3\envs\django\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\code\django\studentManage1\Student_management-master\management\admin.py", line 5, in <module>
    from models import Student,Lesson,Teacher,Score
ModuleNotFoundError: No module named 'models'

**Comment by whiterr** [comment]
ModuleNotFoundError: No module named 'models'

同问
